### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SelinaNguyen** [UniLuFS2020-ReplicationSeminar/Selina_Lisa_Replication-Paper#2]
@DeAngelisA 

https://github.com/UniLuFS2020-ReplicationSeminar/Selina_Lisa_Replication-Paper/blob/e27fe8839a087ff905c7f2fb12d38fa1d39180a2/Output/Figure1-Senate_Ideal_Points.R#L11-L24
We don't understand what they are doing here, but we think it is a way of loading the datasets.
Especially the lapply() function is confusing, because isn't it used to transform other formats of data? This is strange, because the data we downloaded from dataverse is in .RData already.
We also don't understand what the rbindlist() function does exactly.
Manually loading the dataset into R and then proceeding with the rest of the syntax did unfortunately not work, which is why we need your help.

https://github.com/UniLuFS2020-ReplicationSeminar/Selina_Lisa_Replication-Paper/blob/e27fe8839a087ff905c7f2fb12d38fa1d39180a2/Output/Figure1-Senate_Ideal_Points.R#L35-L41
Is it correct to assume here, that the := function replaces the column of the specified dataset?
If yes, then what does the by = c("domain") and by = "domain" argument mean?

**Comment by DeAngelisA** [comment]
`lapply()` is used for iteration, similar to the `for` loop. In practice, `lapply()` calls a function, which can be an existing function, or a function defined at the moment as in this case, changing the argument iterating over all the elements of a vector/list. In this case, line 22 takes a list of file paths (in `paths`) and for each reads a STATA file (using `haven::read_dta()`) and storing the new object into a list `ideals`. Then, in line 24, they "melt" this list of datasets into a single data frame with `rbindlist()`, for a modern implementation of this check out [`dplyr::bind_rows()`](https://dplyr.tidyverse.org/reference/bind.html). 

Coming to your questions:
1. if the data is already in `.RData` format, you can skip line 22.
2. `rbindlist()` converts a list of data frames into a single dataframe "binding" all the separate data frames together.
3. The `:=` is not so important (you can read about here [here](https://stackoverflow.com/a/7033536)). They are simply standardizing by group. You can achieve just that with `group_by()` and `summarize(newvar = (oldvar - mean(oldvar, na.rm = TRUE))/ sd(oldvar, na.rm = TRUE))`, as seen in class. Lines 39 and 40 are just checking that everything worked well (you should get two vectors with numbers close to, respectively, 0 and 1). 

Good luck and keep me posted!
