### ISSUE TITLE
Setting Working Directory and loading RData into RMarkdown

### ISSUE THREAD

**Issue by Lisa-Thai** [UniLuFS2020-ReplicationSeminar/Selina_Lisa_Replication-Paper#5]
Dear @DeAngelisA ,
We have some problems with setting the working directory and loading RData into RMarkdown file for the report. Also after reading multiple forums and trying various codes didn't work. Therefore, we are seeking some help. 

Best wishes,
Lisa & Selina

**Comment by DeAngelisA** [comment]
@Lisa-Thai & @SelinaNguyen : I will email you.
